# .devcontainer/docker-compose.yml
version: '3.8'

services:
  # ... (database services are unchanged) ...

  # --- Microservice Services ---
  user-service:
    build:
      context: ../../user-service # Corrected path: Go up two levels from .devcontainer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: user-db
      DB_USER: user_service_user
      DB_PASSWORD: user_service_password
      DB_NAME: user_db
      JWT_SECRET: aVeryStrongAndComplexSecretKeyForYourJWT
    depends_on:
      user-db:
        condition: service_healthy

  vehicle-service:
    build:
      context: ../../vehicle-service # Corrected path
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vehicle-db:3306/vehicle_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: vehicle_service_user
      SPRING_DATASOURCE_PASSWORD: vehicle_service_password
      SERVER_PORT: 8081
    depends_on:
      vehicle-db:
        condition: service_healthy

  booking-service:
    build:
      context: ../../booking-service # Corrected path
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://booking-db:3306/booking_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: booking_service_user
      SPRING_DATASOURCE_PASSWORD: booking_service_password
      SERVER_PORT: 8082
    depends_on:
      booking-db:
        condition: service_healthy

  service-management-service:
    build:
      context: ../../service-management-service # Corrected path
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://service-management-db:3306/service_management_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: sm_service_user
      SPRING_DATASOURCE_PASSWORD: sm_service_password
      SERVER_PORT: 8083
    depends_on:
      service-management-db:
        condition: service_healthy

  notification-service:
    build:
      context: ../../notification-service # Corrected path
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notification-db:3306/notification_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: notification_service_user
      SPRING_DATASOURCE_PASSWORD: notification_service_password
      SERVER_PORT: 8084
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your-email@gmail.com
      SPRING_MAIL_PASSWORD: your-email-app-password
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    depends_on:
      notification-db:
        condition: service_healthy

# ... (volumes are unchanged) ...
volumes:
  user_db_data:
  vehicle_db_data:
  booking_db_data:
  service_management_db_data:
  notification_db_data: